repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml

-   repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]

-   repo: local
    hooks:
    - id: ruff
      name: ruff
      entry: poetry run ruff
      language: system
      types: [python]

    - id: pylint
      name: pylint
      entry: poetry run pylint npeg
      language: system
      types: [python]

    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types: [python]

    - id: pyright
      name: pyright
      entry: poetry run pyright
      language: system
      types: [python]


    - id: black
      name: black
      entry: poetry run black --check --diff
      language: system
      types: [python]
