repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint npeg
      language: system
      types: [python]

    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types: [python]

    - id: ruff
      name: ruff
      entry: poetry run ruff
      language: system
      types: [python]

    - id: black
      name: black
      entry: poetry run black --check
      language: system
      types: [python]
